#maven plugin help mojo generation informations
#Sat Jan 31 16:55:57 ICT 2026
destinationDirectory=C\:\\Users\\LY DAT\\Desktop\\store\\csw405\\lab4\\2331200190_lydat_lab4\\pitest-1.22.0\\pitest-maven\\target\\generated-sources\\plugin
helpPackageName=
